print('The CIS14 C++ Programming class')
print()
print('The\nCIS14\nC++\nProgramming\nclass')
print()
print(' _________________________________')
print('|                                 |')
print('| The CIS14 C++ Programming class |')
print('|_________________________________|')
